services:
  - type: web
    name: linkshrink
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
